"""
Regression tests: the ``porosimeter`` package must reproduce, on the example
inputs, the exact output produced by the original single-file tool.

The golden files in ``tests/golden/`` were generated by the pre-refactor code:

    python src/main.py init tests/golden
    python src/main.py calibrate tests/golden/calibration_input.json
    python src/main.py measure   tests/golden/measurement_input.json

The measurement fixture was later trimmed to the pore-volume scope of the
toolkit (grain-volume and cuttings support was removed); every number it
still asserts is the untouched pre-refactor output for that sample.

Only the volatile ``generated`` timestamp is stripped before comparison.

Run with either ``python -m unittest discover tests`` or ``python -m pytest``.
"""

import json
import os
import subprocess
import sys
import unittest

# Make the src/ layout importable without an install.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO_ROOT, "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from porosimeter import run_calibration, run_measurement  # noqa: E402
from porosimeter.errors import InputError  # noqa: E402

GOLDEN = os.path.join(os.path.dirname(os.path.abspath(__file__)), "golden")


def _load(name):
    with open(os.path.join(GOLDEN, name), "r", encoding="utf-8") as fh:
        return json.load(fh)


def _strip_generated(result):
    """Return a copy of a result dict without the volatile timestamp."""
    return {k: v for k, v in result.items() if k != "generated"}


class RegressionTest(unittest.TestCase):
    def test_calibration_matches_golden(self):
        data = _load("calibration_input.json")
        expected = _load("calibration_result.json")
        got = run_calibration(data)
        self.assertEqual(_strip_generated(got), _strip_generated(expected))

    def test_measurement_matches_golden(self):
        data = _load("measurement_input.json")
        expected = _load("measurement_result.json")
        # base_dir is the golden directory so the "calibration" file reference
        # (calibration_result.json) resolves.
        got = run_measurement(data, GOLDEN)
        self.assertEqual(_strip_generated(got), _strip_generated(expected))

    def test_cli_smoke(self):
        """`python -m porosimeter measure ...` runs and exits 0."""
        env = dict(os.environ, PYTHONPATH=SRC)
        proc = subprocess.run(
            [sys.executable, "-m", "porosimeter", "measure",
             os.path.join(GOLDEN, "measurement_input.json"),
             "-o", os.path.join(GOLDEN, "_cli_smoke_result.json")],
            cwd=REPO_ROOT, env=env, capture_output=True, text=True)
        self.addCleanup(
            lambda: os.path.exists(
                os.path.join(GOLDEN, "_cli_smoke_result.json"))
            and os.remove(os.path.join(GOLDEN, "_cli_smoke_result.json")))
        self.assertEqual(proc.returncode, 0, proc.stderr)


class PoreVolumeContractTest(unittest.TestCase):
    """The measurement input contract: core plugs, pore volume, nothing else."""

    CAL = {"R": 19836.0, "Vr_cm3": 10.917798, "V_LIN_cm3": 0.061065}
    READINGS = {"P_DV": 11467.4, "P1": 9537.6}

    def _run(self, sample):
        data = {"calibration": self.CAL, "samples": [sample]}
        return run_measurement(data, GOLDEN)["samples"][0]

    def test_pore_volume_block_is_required(self):
        with self.assertRaises(InputError):
            self._run({"sample_id": "X",
                       "bulk_volume": {"value_cm3": 25.7407}})

    def test_both_readings_are_required(self):
        with self.assertRaises(InputError):
            self._run({"sample_id": "X", "pore_volume": {"P_DV": 11467.4}})

    def test_bulk_volume_optional_gives_pore_volume_only(self):
        s = self._run({"sample_id": "X", "pore_volume": dict(self.READINGS)})
        self.assertAlmostEqual(s["results"]["V_p_cm3"], 3.8599, places=4)
        for key in ("V_T_cm3", "V_T_method", "porosity_pct",
                    "bulk_density_g_cm3"):
            self.assertNotIn(key, s["results"])
        self.assertTrue(any("bulk_volume" in w for w in s["warnings"]))

    def test_swapped_readings_are_flagged(self):
        s = self._run({"sample_id": "X",
                       "pore_volume": {"P_DV": 9537.6, "P1": 11467.4},
                       "bulk_volume": {"value_cm3": 25.7407}})
        self.assertLess(s["results"]["V_p_cm3"], 0.0)
        self.assertTrue(any("not positive" in w for w in s["warnings"]))

    def test_bulk_volume_paths_agree(self):
        """Caliper dimensions and a given value are the same quantity."""
        geometry = self._run({
            "sample_id": "X", "pore_volume": dict(self.READINGS),
            "bulk_volume": {"diameter_cm": 2.54, "length_cm": 5.08}})
        given = self._run({
            "sample_id": "X", "pore_volume": dict(self.READINGS),
            "bulk_volume": {"value_cm3": geometry["results"]["V_T_cm3"]}})
        self.assertEqual(geometry["results"]["V_T_method"],
                         "cylinder geometry")
        self.assertEqual(given["results"]["V_T_method"], "given")
        self.assertAlmostEqual(geometry["results"]["porosity_pct"],
                               given["results"]["porosity_pct"], places=2)

    def test_dry_mass_only_affects_bulk_density(self):
        with_mass = self._run({
            "sample_id": "X", "dry_mass_g": 58.12,
            "pore_volume": dict(self.READINGS),
            "bulk_volume": {"value_cm3": 25.7407}})
        without = self._run({
            "sample_id": "X", "pore_volume": dict(self.READINGS),
            "bulk_volume": {"value_cm3": 25.7407}})
        self.assertIn("bulk_density_g_cm3", with_mass["results"])
        self.assertNotIn("bulk_density_g_cm3", without["results"])
        self.assertEqual(with_mass["results"]["porosity_pct"],
                         without["results"]["porosity_pct"])


class MultiPointCalibrationTest(unittest.TestCase):
    """The general N-point "configurations" input shape (three or more)."""

    R = 19836.0

    def _run(self, cell):
        data = {"reference_pressure": {"R": self.R}, "cells": [cell]}
        return run_calibration(data)["cells"][0]

    def test_three_configurations_match_legacy_solve(self):
        """Three configurations reproduce the closed-form two-disc result."""
        legacy = self._run({
            "cell": "A",
            "disc_volumes_cm3": {"V0": 0.0, "V1": 3.398, "V2": 6.768},
            "pressures": {"P_DV": 17872.7, "P1": 13967.4, "P2": 11486.7},
        })
        cfg = self._run({
            "cell": "A",
            "configurations": [
                {"P": 17872.7, "V": 0.0},
                {"P": 13967.4, "V": 3.398},
                {"P": 11486.7, "V": 6.768},
            ],
        })
        for key in ("Vr_cm3", "V_LIN_cm3", "V_D_cm3"):
            self.assertAlmostEqual(cfg[key], legacy[key], places=6)
        # The configurations shape reports fit quality; the legacy shape does
        # not (its three-point solve is always exact).
        self.assertIn("fit", cfg)
        self.assertNotIn("fit", legacy)
        self.assertEqual(cfg["fit"]["n_points"], 3)
        self.assertLess(cfg["fit"]["max_residual_cm3"], 1e-6)

    def test_five_point_overdetermined_fit_recovers_curve(self):
        """A clean five-point set recovers the curve with a tiny residual."""
        import math

        Vr, V_LIN, V_D = 22.2263, 0.155776, 3.0

        def pressure_for_void(V):
            a, b, c = V_LIN, Vr, -(V + V_D)
            x = (-b + math.sqrt(b * b - 4 * a * c)) / (2 * a)
            return self.R / (1 + x)

        cfgs = [{"P": pressure_for_void(V), "V": V}
                for V in (0.0, 3.4, 6.8, 9.5, 12.3)]
        c = self._run({"cell": "C", "configurations": cfgs})
        self.assertEqual(c["fit"]["n_points"], 5)
        self.assertAlmostEqual(c["Vr_cm3"], Vr, places=3)
        self.assertAlmostEqual(c["V_LIN_cm3"], V_LIN, places=3)
        self.assertAlmostEqual(c["V_D_cm3"], V_D, places=3)
        self.assertLess(c["fit"]["max_residual_cm3"], 1e-4)
        self.assertEqual(c["warnings"], [])

    def test_bad_point_raises_residual_warning(self):
        """A misread point inflates the residual and triggers a warning."""
        import math

        Vr, V_LIN, V_D = 22.2263, 0.155776, 3.0

        def pressure_for_void(V):
            a, b, c = V_LIN, Vr, -(V + V_D)
            x = (-b + math.sqrt(b * b - 4 * a * c)) / (2 * a)
            return self.R / (1 + x)

        cfgs = [{"P": pressure_for_void(V), "V": V}
                for V in (0.0, 3.4, 6.8, 9.5, 12.3)]
        cfgs[3]["P"] -= 300.0  # misread pressure on the fourth point
        c = self._run({"cell": "C", "configurations": cfgs})
        self.assertGreater(c["fit"]["max_residual_cm3"], 0.1)
        self.assertTrue(any("deviates" in w and "fitted curve" in w
                            for w in c["warnings"]))

    def test_too_few_points_rejected(self):
        with self.assertRaises(InputError):
            self._run({"cell": "C", "configurations": [
                {"P": 17000.0, "V": 0.0}, {"P": 13000.0, "V": 3.0}]})

    def test_singular_pressures_rejected(self):
        with self.assertRaises(InputError):
            self._run({"cell": "C", "configurations": [
                {"P": 17000.0, "V": 0.0}, {"P": 17000.0, "V": 3.0},
                {"P": 17000.0, "V": 6.0}]})


class TemplateTest(unittest.TestCase):
    """`init` must emit templates that run end to end without editing."""

    def test_init_templates_calibrate_and_measure(self):
        import tempfile

        from porosimeter.cli import load_json, save_json
        from porosimeter.examples import write_examples

        with tempfile.TemporaryDirectory() as tmp:
            cal_in, meas_in = write_examples(tmp)
            cal_result = run_calibration(load_json(cal_in))
            save_json(os.path.join(tmp, "calibration_result.json"),
                      cal_result)
            self.assertEqual([c["warnings"] for c in cal_result["cells"]],
                             [[]])
            result = run_measurement(load_json(meas_in), tmp)
            for s in result["samples"]:
                self.assertEqual(s["warnings"], [])
                self.assertGreater(s["results"]["porosity_pct"], 0.0)


if __name__ == "__main__":
    unittest.main()
