"""
Regression tests: the ``porosimeter`` package must reproduce, on the example
inputs, the exact output produced by the original single-file tool.

The golden files in ``tests/golden/`` were generated by the pre-refactor code:

    python src/main.py init tests/golden
    python src/main.py calibrate tests/golden/calibration_input.json
    python src/main.py measure   tests/golden/measurement_input.json

The measurement fixture was later retargeted at the core-plug procedure
this toolkit implements (two Hassler-holder expansions, spacer discs alone
then discs plus the core).  Its V_g_cm3 = 21.879 is the untouched
pre-refactor output for that reading pair; Vp, porosity and bulk density
are derived from it and the caliper bulk volume.  The plug's caliper
dimensions were later added to the recorded results; every number in the
golden files is still the untouched original.

Only the volatile ``generated`` timestamp is stripped before comparison.

Run with either ``python -m unittest discover tests`` or ``python -m pytest``.
"""

import json
import os
import subprocess
import sys
import unittest

# Make the src/ layout importable without an install.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO_ROOT, "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from porosimeter import run_calibration, run_measurement  # noqa: E402
from porosimeter.errors import InputError  # noqa: E402

GOLDEN = os.path.join(os.path.dirname(os.path.abspath(__file__)), "golden")


def _load(name):
    with open(os.path.join(GOLDEN, name), "r", encoding="utf-8") as fh:
        return json.load(fh)


def _strip_generated(result):
    """Return a copy of a result dict without the volatile timestamp."""
    return {k: v for k, v in result.items() if k != "generated"}


class RegressionTest(unittest.TestCase):
    def test_calibration_matches_golden(self):
        data = _load("calibration_input.json")
        expected = _load("calibration_result.json")
        got = run_calibration(data)
        self.assertEqual(_strip_generated(got), _strip_generated(expected))

    def test_measurement_matches_golden(self):
        data = _load("measurement_input.json")
        expected = _load("measurement_result.json")
        # base_dir is the golden directory so the "calibration" file reference
        # (calibration_result.json) resolves.
        got = run_measurement(data, GOLDEN)
        self.assertEqual(_strip_generated(got), _strip_generated(expected))

    def test_cli_smoke(self):
        """`python -m porosimeter measure ...` runs and exits 0."""
        env = dict(os.environ, PYTHONPATH=SRC)
        proc = subprocess.run(
            [sys.executable, "-m", "porosimeter", "measure",
             os.path.join(GOLDEN, "measurement_input.json"),
             "-o", os.path.join(GOLDEN, "_cli_smoke_result.json")],
            cwd=REPO_ROOT, env=env, capture_output=True, text=True)
        self.addCleanup(
            lambda: os.path.exists(
                os.path.join(GOLDEN, "_cli_smoke_result.json"))
            and os.remove(os.path.join(GOLDEN, "_cli_smoke_result.json")))
        self.assertEqual(proc.returncode, 0, proc.stderr)


class HolderContractTest(unittest.TestCase):
    """The measurement contract: two holder readings + a bulk volume."""

    CAL = {"R": 19836.0, "Vr_cm3": 10.917798, "V_LIN_cm3": 0.061065}
    READINGS = {"P_DV": 6082.5, "P1": 15432.7}
    BULK = {"diameter_cm": 2.54, "length_cm": 5.08}

    def _run(self, sample):
        data = {"calibration": self.CAL, "samples": [sample]}
        return run_measurement(data, GOLDEN)["samples"][0]

    def test_core_holder_block_is_required(self):
        with self.assertRaises(InputError):
            self._run({"sample_id": "X", "bulk_volume": dict(self.BULK)})

    def test_both_readings_are_required(self):
        with self.assertRaises(InputError):
            self._run({"sample_id": "X", "core_holder": {"P_DV": 6082.5},
                       "bulk_volume": dict(self.BULK)})

    def test_bulk_volume_is_required(self):
        """The readings give Vg; without V_T there is no pore volume."""
        with self.assertRaises(InputError):
            self._run({"sample_id": "X", "core_holder": dict(self.READINGS)})

    def test_pore_volume_is_bulk_minus_grain(self):
        s = self._run({"sample_id": "X", "core_holder": dict(self.READINGS),
                       "bulk_volume": dict(self.BULK)})
        Vg = s["core_holder"]["V_g_cm3"]
        self.assertAlmostEqual(s["results"]["V_p_cm3"],
                               s["results"]["V_T_cm3"] - Vg, places=4)
        self.assertAlmostEqual(
            s["results"]["porosity_pct"],
            100.0 * s["results"]["V_p_cm3"] / s["results"]["V_T_cm3"],
            places=2)

    def test_swapped_readings_are_flagged(self):
        """Adding the core must raise the reading: P1 > P_DV."""
        s = self._run({"sample_id": "X",
                       "core_holder": {"P_DV": 15432.7, "P1": 6082.5},
                       "bulk_volume": dict(self.BULK)})
        self.assertLess(s["core_holder"]["V_g_cm3"], 0.0)
        self.assertTrue(any("not positive" in w for w in s["warnings"]))

    def test_bulk_volume_paths_agree(self):
        """Caliper dimensions and a given value are the same quantity."""
        geometry = self._run({
            "sample_id": "X", "core_holder": dict(self.READINGS),
            "bulk_volume": dict(self.BULK)})
        given = self._run({
            "sample_id": "X", "core_holder": dict(self.READINGS),
            "bulk_volume": {"value_cm3": geometry["results"]["V_T_cm3"]}})
        self.assertEqual(geometry["results"]["V_T_method"],
                         "cylinder geometry")
        self.assertEqual(given["results"]["V_T_method"], "given")
        self.assertAlmostEqual(geometry["results"]["porosity_pct"],
                               given["results"]["porosity_pct"], places=2)

    def test_spacer_discs_cancel(self):
        """Discs that do not move between the readings drop out of Vg."""
        from porosimeter.physics import expanded_volume
        R, Vr, VL = 19836.0, 10.917798, 0.061065

        def P_of(void):
            lo, hi = 1.0, R - 1e-9
            for _ in range(200):
                mid = (lo + hi) / 2.0
                if expanded_volume(R, mid, Vr, VL) > void:
                    lo = mid
                else:
                    hi = mid
            return (lo + hi) / 2.0

        Vg_true, V_T = 21.879, 25.7407
        # The blank gas space must still hold the core, so it stays above
        # V_T; the discs only decide how much slack is left beyond that.
        for discs in (0.0, 5.0, 12.0):      # different amounts of packing
            blank = 40.0 - discs            # gas space with discs, no core
            s = self._run({
                "sample_id": "X",
                "core_holder": {"P_DV": P_of(blank),
                                "P1": P_of(blank - Vg_true)},
                "bulk_volume": {"value_cm3": V_T}})
            self.assertAlmostEqual(s["core_holder"]["V_g_cm3"], Vg_true,
                                   places=3)

    def test_plug_dimensions_are_reported(self):
        """The caliper dimensions belong on the record card, in cm."""
        import math

        s = self._run({"sample_id": "X", "core_holder": dict(self.READINGS),
                       "bulk_volume": dict(self.BULK)})
        r = s["results"]
        self.assertEqual(r["diameter_cm"], self.BULK["diameter_cm"])
        self.assertEqual(r["length_cm"], self.BULK["length_cm"])
        self.assertAlmostEqual(
            r["V_T_cm3"],
            math.pi * r["diameter_cm"] ** 2 / 4.0 * r["length_cm"], places=4)

    def test_dimensions_absent_when_only_a_bulk_volume_is_given(self):
        s = self._run({"sample_id": "X", "core_holder": dict(self.READINGS),
                       "bulk_volume": {"value_cm3": 25.7407}})
        self.assertNotIn("diameter_cm", s["results"])
        self.assertNotIn("length_cm", s["results"])

    def test_dimensions_recorded_alongside_a_given_bulk_volume(self):
        """V_T still comes from value_cm3; the plug is recorded anyway."""
        s = self._run({"sample_id": "X", "core_holder": dict(self.READINGS),
                       "bulk_volume": {"value_cm3": 24.0,
                                       "diameter_cm": 2.54,
                                       "length_cm": 5.08}})
        self.assertEqual(s["results"]["V_T_method"], "given")
        self.assertEqual(s["results"]["V_T_cm3"], 24.0)
        self.assertEqual(s["results"]["diameter_cm"], 2.54)
        self.assertEqual(s["results"]["length_cm"], 5.08)

    def test_dry_mass_only_affects_bulk_density(self):
        with_mass = self._run({
            "sample_id": "X", "dry_mass_g": 58.12,
            "core_holder": dict(self.READINGS),
            "bulk_volume": dict(self.BULK)})
        without = self._run({
            "sample_id": "X", "core_holder": dict(self.READINGS),
            "bulk_volume": dict(self.BULK)})
        self.assertIn("bulk_density_g_cm3", with_mass["results"])
        self.assertNotIn("bulk_density_g_cm3", without["results"])
        self.assertEqual(with_mass["results"]["porosity_pct"],
                         without["results"]["porosity_pct"])


class MultiPointCalibrationTest(unittest.TestCase):
    """The general N-point "configurations" input shape (three or more)."""

    R = 19836.0

    def _run(self, cell):
        data = {"reference_pressure": {"R": self.R}, "cells": [cell]}
        return run_calibration(data)["cells"][0]

    def test_three_configurations_match_legacy_solve(self):
        """Three configurations reproduce the closed-form two-disc result."""
        legacy = self._run({
            "cell": "A",
            "disc_volumes_cm3": {"V0": 0.0, "V1": 3.398, "V2": 6.768},
            "pressures": {"P_DV": 17872.7, "P1": 13967.4, "P2": 11486.7},
        })
        cfg = self._run({
            "cell": "A",
            "configurations": [
                {"P": 17872.7, "V": 0.0},
                {"P": 13967.4, "V": 3.398},
                {"P": 11486.7, "V": 6.768},
            ],
        })
        for key in ("Vr_cm3", "V_LIN_cm3", "V_D_cm3"):
            self.assertAlmostEqual(cfg[key], legacy[key], places=6)
        # The configurations shape reports fit quality; the legacy shape does
        # not (its three-point solve is always exact).
        self.assertIn("fit", cfg)
        self.assertNotIn("fit", legacy)
        self.assertEqual(cfg["fit"]["n_points"], 3)
        self.assertLess(cfg["fit"]["max_residual_cm3"], 1e-6)

    def test_five_point_overdetermined_fit_recovers_curve(self):
        """A clean five-point set recovers the curve with a tiny residual."""
        import math

        Vr, V_LIN, V_D = 22.2263, 0.155776, 3.0

        def pressure_for_void(V):
            a, b, c = V_LIN, Vr, -(V + V_D)
            x = (-b + math.sqrt(b * b - 4 * a * c)) / (2 * a)
            return self.R / (1 + x)

        cfgs = [{"P": pressure_for_void(V), "V": V}
                for V in (0.0, 3.4, 6.8, 9.5, 12.3)]
        c = self._run({"cell": "C", "configurations": cfgs})
        self.assertEqual(c["fit"]["n_points"], 5)
        self.assertAlmostEqual(c["Vr_cm3"], Vr, places=3)
        self.assertAlmostEqual(c["V_LIN_cm3"], V_LIN, places=3)
        self.assertAlmostEqual(c["V_D_cm3"], V_D, places=3)
        self.assertLess(c["fit"]["max_residual_cm3"], 1e-4)
        self.assertEqual(c["warnings"], [])

    def test_bad_point_raises_residual_warning(self):
        """A misread point inflates the residual and triggers a warning."""
        import math

        Vr, V_LIN, V_D = 22.2263, 0.155776, 3.0

        def pressure_for_void(V):
            a, b, c = V_LIN, Vr, -(V + V_D)
            x = (-b + math.sqrt(b * b - 4 * a * c)) / (2 * a)
            return self.R / (1 + x)

        cfgs = [{"P": pressure_for_void(V), "V": V}
                for V in (0.0, 3.4, 6.8, 9.5, 12.3)]
        cfgs[3]["P"] -= 300.0  # misread pressure on the fourth point
        c = self._run({"cell": "C", "configurations": cfgs})
        self.assertGreater(c["fit"]["max_residual_cm3"], 0.1)
        self.assertTrue(any("deviates" in w and "fitted curve" in w
                            for w in c["warnings"]))

    def test_too_few_points_rejected(self):
        with self.assertRaises(InputError):
            self._run({"cell": "C", "configurations": [
                {"P": 17000.0, "V": 0.0}, {"P": 13000.0, "V": 3.0}]})

    def test_singular_pressures_rejected(self):
        with self.assertRaises(InputError):
            self._run({"cell": "C", "configurations": [
                {"P": 17000.0, "V": 0.0}, {"P": 17000.0, "V": 3.0},
                {"P": 17000.0, "V": 6.0}]})


class CalibrationModelTest(unittest.TestCase):
    """Model selection for the multi-point ("configurations") calibration."""

    R = 19836.0
    Vr, D, V_D = 22.2263, -0.007, 3.0

    def _calibrate(self, cell, model=None):
        data = {"reference_pressure": {"R": self.R}, "cells": [cell]}
        if model is not None:
            data["model"] = model
        return run_calibration(data)

    def _harmonic_points(self, voids):
        """Pressures that lie exactly on V = Vr*x/(1 + D*x) - V_D."""
        pts = []
        for V in voids:
            w = V + self.V_D
            x = w / (self.Vr - w * self.D)
            pts.append({"P": self.R / (1.0 + x), "V": V})
        return pts

    def _linear_points(self, voids):
        """Pressures that lie exactly on V = Vr*x - V_D."""
        return [{"P": self.R / (1.0 + (V + self.V_D) / self.Vr), "V": V}
                for V in voids]

    def test_default_is_the_quadratic_manual_model(self):
        result = self._calibrate(
            {"cell": "C",
             "configurations": self._harmonic_points([0.0, 3.4, 6.8])})
        c = result["cells"][0]
        self.assertEqual(c["model"], "quadratic")
        self.assertIn("V_LIN_cm3", c)
        self.assertNotIn("D", c)

    def test_harmonic_model_recovers_its_own_curve(self):
        c = self._calibrate(
            {"cell": "C",
             "configurations": self._harmonic_points([0.0, 3.4, 6.8, 9.5,
                                                      12.3])},
            model="harmonic")["cells"][0]
        self.assertEqual(c["model"], "harmonic")
        self.assertAlmostEqual(c["Vr_cm3"], self.Vr, places=4)
        self.assertAlmostEqual(c["D"], self.D, places=6)
        self.assertAlmostEqual(c["V_D_cm3"], self.V_D, places=4)
        self.assertLess(c["fit"]["max_residual_cm3"], 1e-6)
        self.assertIn("u_D", c["uncertainty"])
        self.assertIn("cov_Vr_D", c["uncertainty"])
        self.assertNotIn("V_LIN_cm3", c)
        # -Vr*D is the second-order coefficient comparable with factory V_LIN.
        self.assertAlmostEqual(
            c["factory_comparison"]["V_LIN_equivalent_cm3"],
            -self.Vr * self.D, places=5)

    def test_harmonic_exact_with_three_points(self):
        """Three points determine the three harmonic parameters exactly."""
        c = self._calibrate(
            {"cell": "C",
             "configurations": self._harmonic_points([0.0, 3.4, 6.8])},
            model="harmonic")["cells"][0]
        self.assertAlmostEqual(c["Vr_cm3"], self.Vr, places=4)
        self.assertAlmostEqual(c["D"], self.D, places=6)
        self.assertLess(c["fit"]["max_residual_cm3"], 1e-6)

    def test_linear_model_needs_only_two_points(self):
        two = self._linear_points([0.0, 8.0])
        c = self._calibrate({"cell": "C", "configurations": two},
                            model="linear")["cells"][0]
        self.assertEqual(c["model"], "linear")
        self.assertAlmostEqual(c["Vr_cm3"], self.Vr, places=4)
        self.assertAlmostEqual(c["V_D_cm3"], self.V_D, places=4)
        self.assertNotIn("V_LIN_cm3", c)
        # No second-order term, so no factory V_LIN comparison to make.
        self.assertNotIn("V_LIN_deviation_pct", c["factory_comparison"])
        self.assertEqual(c["warnings"], [])

    def test_quadratic_still_needs_three_points(self):
        two = self._linear_points([0.0, 8.0])
        with self.assertRaises(InputError):
            self._calibrate({"cell": "C", "configurations": two})

    def test_per_cell_model_overrides_the_file_default(self):
        data = {"reference_pressure": {"R": self.R}, "model": "harmonic",
                "cells": [
                    {"cell": "C",
                     "configurations": self._harmonic_points([0.0, 3.4, 6.8])},
                    {"cell": "A", "model": "linear",
                     "configurations": self._linear_points([0.0, 4.0, 8.0])},
                ]}
        cells = run_calibration(data)["cells"]
        self.assertEqual([c["model"] for c in cells], ["harmonic", "linear"])

    def test_unknown_model_rejected(self):
        with self.assertRaises(InputError):
            self._calibrate({"cell": "C",
                             "configurations": self._harmonic_points(
                                 [0.0, 3.4, 6.8])}, model="hyperbolic")

    def test_legacy_two_disc_shape_rejects_a_non_quadratic_model(self):
        """The manual's closed form is quadratic; ask for points instead."""
        with self.assertRaises(InputError):
            self._calibrate({
                "cell": "A",
                "disc_volumes_cm3": {"V0": 0.0, "V1": 3.398, "V2": 6.768},
                "pressures": {"P_DV": 17872.7, "P1": 13967.4, "P2": 11486.7},
            }, model="harmonic")


class MeasurementModelTest(unittest.TestCase):
    """A measurement must reduce its readings with the calibrated model."""

    R = 19836.0
    READINGS = {"P_DV": 9374.0, "P1": 17395.7}
    BULK = {"value_cm3": 25.7407}
    Vr, D, V_D = 22.2263, -0.007, 3.0

    def _measure(self, calibration):
        data = {"calibration": calibration,
                "samples": [{"sample_id": "X",
                             "core_holder": dict(self.READINGS),
                             "bulk_volume": dict(self.BULK)}]}
        return run_measurement(data, GOLDEN)

    def test_inline_harmonic_matches_the_harmonic_formula(self):
        from porosimeter.physics import expansion_ratio

        result = self._measure({"R": self.R, "model": "harmonic",
                                "Vr_cm3": self.Vr, "D": self.D})
        self.assertEqual(result["calibration"]["model"], "harmonic")
        self.assertIn("D", result["calibration"])
        self.assertNotIn("V_LIN_cm3", result["calibration"])

        def V(P):
            x = expansion_ratio(self.R, P)
            return self.Vr * x / (1.0 + self.D * x)

        expected = V(self.READINGS["P_DV"]) - V(self.READINGS["P1"])
        self.assertAlmostEqual(
            result["samples"][0]["core_holder"]["V_g_cm3"], expected,
            places=4)

    def test_models_give_different_results_on_the_same_constants(self):
        """The model drives the reduction, it is not just a label."""
        harmonic = self._measure({"R": self.R, "model": "harmonic",
                                  "Vr_cm3": self.Vr, "D": self.D})
        linear = self._measure({"R": self.R, "model": "linear",
                                "Vr_cm3": self.Vr})
        quadratic = self._measure({"R": self.R, "Vr_cm3": self.Vr,
                                   "V_LIN_cm3": -self.Vr * self.D})
        got = [r["samples"][0]["results"]["porosity_pct"]
               for r in (harmonic, linear, quadratic)]
        self.assertNotAlmostEqual(got[0], got[1], places=2)
        # To second order the harmonic and quadratic models agree.
        self.assertAlmostEqual(got[0], got[2], places=1)
        self.assertNotEqual(got[0], got[2])

    def test_model_survives_the_calibration_file_round_trip(self):
        import tempfile

        from porosimeter.cli import save_json

        cal_in = {
            "reference_pressure": {"R": self.R},
            "model": "harmonic",
            "cells": [{"cell": "C", "configurations": [
                {"P": self.R / (1.0 + (V + self.V_D)
                                / (self.Vr - (V + self.V_D) * self.D)),
                 "V": V} for V in (0.0, 3.4, 6.8, 9.5)]}],
        }
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "calibration_result.json")
            save_json(path, run_calibration(cal_in))
            data = {"calibration": {"file": path, "cell": "C"},
                    "samples": [{"sample_id": "X",
                                 "core_holder": dict(self.READINGS),
                                 "bulk_volume": dict(self.BULK)}]}
            from_file = run_measurement(data, tmp)
        inline = self._measure({"R": self.R, "model": "harmonic",
                                "Vr_cm3": self.Vr, "D": self.D})
        self.assertEqual(from_file["calibration"]["model"], "harmonic")
        self.assertAlmostEqual(
            from_file["samples"][0]["results"]["porosity_pct"],
            inline["samples"][0]["results"]["porosity_pct"], places=3)

    def test_missing_model_parameter_rejected(self):
        """A harmonic calibration without D cannot be applied."""
        with self.assertRaises(InputError):
            self._measure({"R": self.R, "model": "harmonic",
                           "Vr_cm3": self.Vr})


class TemplateTest(unittest.TestCase):
    """`init` must emit templates that run end to end without editing."""

    def test_init_templates_calibrate_and_measure(self):
        import tempfile

        from porosimeter.cli import load_json, save_json
        from porosimeter.examples import write_examples

        with tempfile.TemporaryDirectory() as tmp:
            cal_in, meas_in = write_examples(tmp)
            cal_result = run_calibration(load_json(cal_in))
            save_json(os.path.join(tmp, "calibration_result.json"),
                      cal_result)
            self.assertEqual([c["warnings"] for c in cal_result["cells"]],
                             [[]])
            result = run_measurement(load_json(meas_in), tmp)
            for s in result["samples"]:
                self.assertEqual(s["warnings"], [])
                self.assertGreater(s["results"]["porosity_pct"], 0.0)

class ExportTest(unittest.TestCase):
    """The "export" command: one sample file per measured plug."""

    def _documents(self, mutate=None):
        from porosimeter.export import build_documents

        data = _load("measurement_input.json")
        if mutate:
            mutate(data)
        result = run_measurement(data, GOLDEN)
        return data, result, build_documents(data, result, "gasperm")

    def _fields(self, text):
        """Parse the emitted YAML back with the standard library only."""
        out = {}
        for line in text.splitlines():
            if line.startswith("#") or not line.strip():
                continue
            key, _, value = line.partition(":")
            value = value.split("#")[0].strip()
            if value.startswith("'"):
                value = value[1:value.rindex("'")].replace("''", "'")
            elif value == "null":
                value = None
            else:
                try:
                    value = float(value)
                except ValueError:
                    pass
            out[key.strip()] = value
        return out

    def test_one_document_per_sample_with_the_gasperm_keys(self):
        data, result, docs = self._documents()
        self.assertEqual([d["sample_id"] for d in docs],
                         [s["sample_id"] for s in result["samples"]])
        self.assertEqual([d["filename"] for d in docs], ["S-01.yaml"])
        self.assertEqual(sorted(self._fields(docs[0]["text"])), sorted([
            "id", "description", "lithology", "formation", "well", "depth",
            "depth_unit", "dimension_unit", "length", "diameter",
            "length_uncertainty", "diameter_uncertainty",
            "porosity_fraction", "porosity_method", "grain_density_g_cm3",
            "bulk_density_g_cm3", "prepared_by", "prepared_on", "notes"]))

    def test_geometry_and_petrophysics_carry_the_measured_values(self):
        data, result, docs = self._documents()
        sample, res = data["samples"][0], result["samples"][0]
        got = self._fields(docs[0]["text"])
        self.assertEqual(got["dimension_unit"], "cm")
        self.assertAlmostEqual(got["length"],
                               sample["bulk_volume"]["length_cm"])
        self.assertAlmostEqual(got["diameter"],
                               sample["bulk_volume"]["diameter_cm"])
        self.assertAlmostEqual(got["porosity_fraction"],
                               res["results"]["porosity_pct"] / 100.0,
                               places=5)
        self.assertAlmostEqual(got["bulk_density_g_cm3"],
                               res["results"]["bulk_density_g_cm3"])
        # Grain density is the one value only the porosimeter knows.
        self.assertAlmostEqual(
            got["grain_density_g_cm3"],
            res["dry_mass_g"] / res["core_holder"]["V_g_cm3"], places=3)
        self.assertEqual(docs[0]["warnings"], [])

    def test_a_given_bulk_volume_leaves_the_geometry_empty_and_warns(self):
        """gasperm needs the dimensions; a volume alone cannot supply them."""
        def mutate(data):
            data["samples"][0]["bulk_volume"] = {"value_cm3": 25.7407}

        _, _, docs = self._documents(mutate)
        got = self._fields(docs[0]["text"])
        self.assertIsNone(got["length"])
        self.assertIsNone(got["diameter"])
        self.assertTrue(any("caliper dimensions" in w
                            for w in docs[0]["warnings"]))

    def test_provenance_is_carried_through(self):
        def mutate(data):
            data["samples"][0].update(
                {"well": "W-1", "formation": "Rotliegend", "depth": 1234.5,
                 "lithology": "sandstone", "notes": "it's dry"})

        _, _, docs = self._documents(mutate)
        got = self._fields(docs[0]["text"])
        self.assertEqual(got["well"], "W-1")
        self.assertEqual(got["formation"], "Rotliegend")
        self.assertEqual(got["lithology"], "sandstone")
        self.assertEqual(got["depth"], 1234.5)
        self.assertEqual(got["depth_unit"], "m")
        self.assertEqual(got["notes"], "it's dry")

    def test_ids_become_distinct_filenames(self):
        def mutate(data):
            # Two ids that differ only in characters a filename cannot keep.
            twin = dict(data["samples"][0], sample_id="W1_A_12_3")
            data["samples"][0]["sample_id"] = "W1/A 12:3"
            data["samples"].append(twin)

        _, _, docs = self._documents(mutate)
        self.assertEqual([d["filename"] for d in docs],
                         ["W1_A_12_3.yaml", "W1_A_12_3_2.yaml"])
        self.assertEqual(self._fields(docs[0]["text"])["id"], "W1/A 12:3")

    def test_unknown_format_rejected(self):
        from porosimeter.export import build_documents

        data = _load("measurement_input.json")
        result = run_measurement(data, GOLDEN)
        with self.assertRaises(InputError):
            build_documents(data, result, "nope")

    def test_cli_export_writes_files(self):
        import tempfile

        env = dict(os.environ, PYTHONPATH=SRC)
        with tempfile.TemporaryDirectory() as tmp:
            proc = subprocess.run(
                [sys.executable, "-m", "porosimeter", "export",
                 os.path.join(GOLDEN, "measurement_input.json"), "-o", tmp],
                cwd=REPO_ROOT, env=env, capture_output=True, text=True)
            self.assertEqual(proc.returncode, 0, proc.stderr)
            self.assertEqual(sorted(os.listdir(tmp)), ["S-01.yaml"])


if __name__ == "__main__":
    unittest.main()
