"""
Regression tests: the refactored ``porosimeter`` package must reproduce, on the
example inputs, the exact output produced by the original single-file tool.

The golden files in ``tests/golden/`` were generated by the pre-refactor code:

    python src/main.py init tests/golden
    python src/main.py calibrate tests/golden/calibration_input.json
    python src/main.py measure   tests/golden/measurement_input.json

Only the volatile ``generated`` timestamp is stripped before comparison.

Run with either ``python -m unittest discover tests`` or ``python -m pytest``.
"""

import json
import os
import subprocess
import sys
import unittest

# Make the src/ layout importable without an install.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO_ROOT, "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from porosimeter import run_calibration, run_measurement  # noqa: E402

GOLDEN = os.path.join(os.path.dirname(os.path.abspath(__file__)), "golden")


def _load(name):
    with open(os.path.join(GOLDEN, name), "r", encoding="utf-8") as fh:
        return json.load(fh)


def _strip_generated(result):
    """Return a copy of a result dict without the volatile timestamp."""
    return {k: v for k, v in result.items() if k != "generated"}


class RegressionTest(unittest.TestCase):
    def test_calibration_matches_golden(self):
        data = _load("calibration_input.json")
        expected = _load("calibration_result.json")
        got = run_calibration(data)
        self.assertEqual(_strip_generated(got), _strip_generated(expected))

    def test_measurement_matches_golden(self):
        data = _load("measurement_input.json")
        expected = _load("measurement_result.json")
        # base_dir is the golden directory so the "calibration" file reference
        # (calibration_result.json) resolves.
        got = run_measurement(data, GOLDEN)
        self.assertEqual(_strip_generated(got), _strip_generated(expected))

    def test_cli_smoke(self):
        """`python -m porosimeter measure ...` runs and exits 0."""
        env = dict(os.environ, PYTHONPATH=SRC)
        proc = subprocess.run(
            [sys.executable, "-m", "porosimeter", "measure",
             os.path.join(GOLDEN, "measurement_input.json"),
             "-o", os.path.join(GOLDEN, "_cli_smoke_result.json")],
            cwd=REPO_ROOT, env=env, capture_output=True, text=True)
        self.addCleanup(
            lambda: os.path.exists(
                os.path.join(GOLDEN, "_cli_smoke_result.json"))
            and os.remove(os.path.join(GOLDEN, "_cli_smoke_result.json")))
        self.assertEqual(proc.returncode, 0, proc.stderr)


if __name__ == "__main__":
    unittest.main()
